export const songsArray = [
    {id: 1, artist: 'Shkodra Elektronike', name: 'Zjerm', country: 'Albania'},
    {id: 2, artist: 'PARG', name: 'SURVIVOR', country: 'Armenia'},
    {id: 3, artist: 'Go-Jo', name: 'Milkshake Man', country: 'Australia'},
    {id: 4, artist: 'JJ', name: 'Wasted Love', country: 'Austria'},
    {id: 5, artist: 'Mamagama', name: 'Run With U', country: 'Azerbaijan'},
    {id: 6, artist: 'Red Sebastian', name: 'Strobe Lights', country: 'Belgium'},
    {id: 7, artist: 'Marko Bošnjak', name: 'Poison Cake', country: 'Croatia'},
    {id: 8, artist: 'Theo Evan', name: 'Shh', country: 'Cyprus'},
    {id: 9, artist: 'ADONXS', name: 'Kiss Kiss Goodbye', country: 'Czechia'},
    {id: 10, artist: 'Sissal', name: 'Hallucination', country: 'Denmark'},
    {id: 11, artist: 'Tommy Cash', name: 'Espresso Macchiato', country: 'Estonia'},
    {id: 12, artist: 'Erika Vikman', name: 'ICH KOMME', country: 'Finland'},
    {id: 13, artist: 'Louane', name: 'Maman', country: 'France'},
    {id: 14, artist: 'Mariam Shengelia', name: 'Freedom', country: 'Georgia'},
    {id: 15, artist: 'Abor & Tynna', name: 'Baller', country: 'Germany'},
    {id: 16, artist: 'Klavdía', name: 'Asteromáta', country: 'Greece'},
    {id: 17, artist: 'VÆB', name: 'RÓA', country: 'Iceland'},
    {id: 18, artist: 'EMMY', name: 'Laika Party', country: 'Ireland'},
    {id: 19, artist: 'Yuval Raphael', name: 'New Day Will Rise', country: 'Israel'},
    {id: 20, artist: 'Lucio Corsi', name: 'Volevo Essere Un Duro', country: 'Italy'},
    {id: 21, artist: 'Tautumeitas', name: 'Bur Man Laimi', country: 'Latvia'},
    {id: 22, artist: 'Katarsis', name: 'Tavo Akys', country: 'Lithuania'},
    {id: 23, artist: 'Laura Thorn', name: 'La Poupée Monte Le Son', country: 'Luxembourg'},
    {id: 24, artist: 'Miriana Conte', name: 'Serving', country: 'Malta'},
    {id: 25, artist: 'Nina Žižić', name: 'Dobrodošli', country: 'Montenegro'},
    {id: 26, artist: 'Claude', name: 'C\'est La Vie', country: 'Netherlands'},
    {id: 27, artist: 'Kyle Alessandro', name: 'Lighter', country: 'Norway'},
    {id: 28, artist: 'Justyna Steczkowska', name: 'GAJA', country: 'Poland'},
    {id: 29, artist: 'NAPA', name: 'Deslocado', country: 'Portugal'},
    {id: 30, artist: 'Gabry Ponte', name: 'Tutta L\'Italia', country: 'San Marino'},
    {id: 31, artist: 'Princ', name: 'Mila', country: 'Serbia'},
    {id: 32, artist: 'Klemen', name: 'How Much Time Do We Have Left', country: 'Slovenia'},
    {id: 33, artist: 'Melody', name: 'ESA DIVA', country: 'Spain'},
    {id: 34, artist: 'KAJ', name: 'Bara Bada Bastu', country: 'Sweden'},
    {id: 35, artist: 'Zoë Më', name: 'Voyage', country: 'Switzerland'},
    {id: 36, artist: 'Ziferblat', name: 'Bird of Pray', country: 'Ukraine'},
    {id: 37, artist: 'Remember Monday', name: 'What The Hell Just Happened?', country: 'United Kingdom'}
];