export const songsArray = [
    {id: 1, artist: 'Shkodra Elektronike', name: 'Zjerm', country: 'Albania', flag: '🇦🇱'},
    {id: 2, artist: 'PARG', name: 'SURVIVOR', country: 'Armenia', flag: '🇦🇲'},
    {id: 3, artist: 'Go-Jo', name: 'Milkshake Man', country: 'Australia', flag: '🇦🇺'},
    {id: 4, artist: 'JJ', name: 'Wasted Love', country: 'Austria', flag: '🇦🇹'},
    {id: 5, artist: 'Mamagama', name: 'Run With U', country: 'Azerbaijan', flag: '🇦🇿'},
    {id: 6, artist: 'Red Sebastian', name: 'Strobe Lights', country: 'Belgium', flag: '🇧🇪'},
    {id: 7, artist: 'Marko Bošnjak', name: 'Poison Cake', country: 'Croatia', flag: '🇭🇷'},
    {id: 8, artist: 'Theo Evan', name: 'Shh', country: 'Cyprus', flag: '🇨🇾'},
    {id: 9, artist: 'ADONXS', name: 'Kiss Kiss Goodbye', country: 'Czechia', flag: '🇨🇿'},
    {id: 10, artist: 'Sissal', name: 'Hallucination', country: 'Denmark', flag: '🇩🇰'},
    {id: 11, artist: 'Tommy Cash', name: 'Espresso Macchiato', country: 'Estonia', flag: '🇪🇪'},
    {id: 12, artist: 'Erika Vikman', name: 'ICH KOMME', country: 'Finland', flag: '🇫🇮'},
    {id: 13, artist: 'Louane', name: 'Maman', country: 'France', flag: '🇫🇷'},
    {id: 14, artist: 'Mariam Shengelia', name: 'Freedom', country: 'Georgia', flag: '🇬🇪'},
    {id: 15, artist: 'Abor & Tynna', name: 'Baller', country: 'Germany', flag: '🇩🇪'},
    {id: 16, artist: 'Klavdía', name: 'Asteromáta', country: 'Greece', flag: '🇬🇷'},
    {id: 17, artist: 'VÆB', name: 'RÓA', country: 'Iceland', flag: '🇮🇸'},
    {id: 18, artist: 'EMMY', name: 'Laika Party', country: 'Ireland', flag: '🇮🇪'},
    {id: 19, artist: 'Yuval Raphael', name: 'New Day Will Rise', country: 'Israel', flag: '🇮🇱'},
    {id: 20, artist: 'Lucio Corsi', name: 'Volevo Essere Un Duro', country: 'Italy', flag: '🇮🇹'},
    {id: 21, artist: 'Tautumeitas', name: 'Bur Man Laimi', country: 'Latvia', flag: '🇱🇻'},
    {id: 22, artist: 'Katarsis', name: 'Tavo Akys', country: 'Lithuania', flag: '🇱🇹'},
    {id: 23, artist: 'Laura Thorn', name: 'La Poupée Monte Le Son', country: 'Luxembourg', flag: '🇱🇺'},
    {id: 24, artist: 'Miriana Conte', name: 'Serving', country: 'Malta', flag: '🇲🇹'},
    {id: 25, artist: 'Nina Žižić', name: 'Dobrodošli', country: 'Montenegro', flag: '🇲🇪'},
    {id: 26, artist: 'Claude', name: 'C\'est La Vie', country: 'Netherlands', flag: '🇳🇱'},
    {id: 27, artist: 'Kyle Alessandro', name: 'Lighter', country: 'Norway', flag: '🇳🇴'},
    {id: 28, artist: 'Justyna Steczkowska', name: 'GAJA', country: 'Poland', flag: '🇵🇱'},
    {id: 29, artist: 'NAPA', name: 'Deslocado', country: 'Portugal', flag: '🇵🇹'},
    {id: 30, artist: 'Gabry Ponte', name: 'Tutta L\'Italia', country: 'San Marino', flag: '🇸🇲'},
    {id: 31, artist: 'Princ', name: 'Mila', country: 'Serbia', flag: '🇷🇸'},
    {id: 32, artist: 'Klemen', name: 'How Much Time Do We Have Left', country: 'Slovenia', flag: '🇸🇮'},
    {id: 33, artist: 'Melody', name: 'ESA DIVA', country: 'Spain', flag: '🇪🇸'},
    {id: 34, artist: 'KAJ', name: 'Bara Bada Bastu', country: 'Sweden', flag: '🇸🇪'},
    {id: 35, artist: 'Zoë Më', name: 'Voyage', country: 'Switzerland', flag: '🇨🇭'},
    {id: 36, artist: 'Ziferblat', name: 'Bird of Pray', country: 'Ukraine', flag: '🇺🇦'},
    {id: 37, artist: 'Remember Monday', name: 'What The Hell Just Happened?', country: 'United Kingdom', flag: '🇬🇧'}
];